CREATE DATABASE IF NOT exist contactdb;
USE contactdb;
CREATE TABLE city(id SMALLINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
city_name VARCHAR(50) NOT NULL) ENGINE INNODB;
CREATE TABLE contact(id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(80) NOT NULL,
firstname VARCHAR(25) NOT NULL,
email VARCHAR(125) UNIQUE NOT NULL,
street VARCHAR(25), NOT NULL,
zip_code INT(5) NOT NULL,
cityid SMALLINT UNSIGNED NOT NULL,
FOREIGN KEY(cityid) REFERENCES city(id)
)ENGINE INNODB; test